include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.look.dart"
  errors:
    invalid_annotation_target: ignore
    duplicate_ignore: ignore
linter:
  rules:
